### ISSUE TITLE
Ordem crescente

### ISSUE THREAD

**Issue by henriquemunizbraga** [rogereis/accervoaal-spring-boot#2]
Caso seja possivel, favor ordenar o resultado da busca em ordem crescente. No arquivo em anexo, nota-se que os arquivos vem em ordem aleatoria.
![rogerio](https://user-images.githubusercontent.com/64201841/80485316-88371180-892f-11ea-8a7d-636b8769341a.png)

**Comment by rogereis** [comment]
Funcionalidade já disponível para teste
